use rusqlite::{params, OptionalExtension, Result};
use tauri::AppHandle;

use crate::db;
use crate::models::{PromptRun, ProposalDetail};
use crate::proposal_commands;

#[tauri::command]
pub fn generate_proposal_prompt(app: AppHandle, proposal_id: i64) -> Result<PromptRun, String> {
    let proposal = proposal_commands::get_proposal_by_id(app.clone(), proposal_id)?
        .ok_or_else(|| "Proposal not found".to_string())?;
    let prompt_title = build_prompt_title(&proposal);
    let prompt_text = build_prompt_text(&proposal);
    let conn = db::open_initialized(&app)?;

    conn.execute(
        "INSERT INTO prompt_runs (
            proposal_id, prompt_title, prompt_text, prompt_format, notes
         )
         VALUES (?1, ?2, ?3, 'markdown', ?4)",
        params![
            proposal_id,
            prompt_title,
            prompt_text,
            "Generated by Proposal Prompt Studio.",
        ],
    )
    .map_err(|error| error.to_string())?;

    let id = conn.last_insert_rowid();
    query_prompt_run_by_id(&conn, id).map_err(|error| error.to_string())
}

#[tauri::command]
pub fn get_prompt_runs(app: AppHandle, proposal_id: i64) -> Result<Vec<PromptRun>, String> {
    let conn = db::open_initialized(&app)?;
    let mut stmt = conn
        .prepare(
            "SELECT id, proposal_id, prompt_title, prompt_text, prompt_format,
                    generated_at, copied_at, exported_path, notes
             FROM prompt_runs
             WHERE proposal_id = ?1
             ORDER BY generated_at DESC, id DESC",
        )
        .map_err(|error| error.to_string())?;
    let rows = stmt
        .query_map(params![proposal_id], map_prompt_run)
        .map_err(|error| error.to_string())?;
    let result = rows
        .collect::<Result<Vec<_>>>()
        .map_err(|error| error.to_string())?;
    Ok(result)
}

#[tauri::command]
pub fn get_latest_prompt_run(
    app: AppHandle,
    proposal_id: i64,
) -> Result<Option<PromptRun>, String> {
    let conn = db::open_initialized(&app)?;
    conn.query_row(
        "SELECT id, proposal_id, prompt_title, prompt_text, prompt_format,
                generated_at, copied_at, exported_path, notes
         FROM prompt_runs
         WHERE proposal_id = ?1
         ORDER BY generated_at DESC, id DESC
         LIMIT 1",
        params![proposal_id],
        map_prompt_run,
    )
    .optional()
    .map_err(|error| error.to_string())
}

#[tauri::command]
pub fn get_prompt_run_by_id(app: AppHandle, id: i64) -> Result<Option<PromptRun>, String> {
    let conn = db::open_initialized(&app)?;
    query_prompt_run_by_id(&conn, id)
        .optional()
        .map_err(|error| error.to_string())
}

fn query_prompt_run_by_id(conn: &rusqlite::Connection, id: i64) -> Result<PromptRun> {
    conn.query_row(
        "SELECT id, proposal_id, prompt_title, prompt_text, prompt_format,
                generated_at, copied_at, exported_path, notes
         FROM prompt_runs
         WHERE id = ?1",
        params![id],
        map_prompt_run,
    )
}

fn map_prompt_run(row: &rusqlite::Row<'_>) -> Result<PromptRun> {
    Ok(PromptRun {
        id: row.get(0)?,
        proposal_id: row.get(1)?,
        prompt_title: row.get(2)?,
        prompt_text: row.get(3)?,
        prompt_format: row.get(4)?,
        generated_at: row.get(5)?,
        copied_at: row.get(6)?,
        exported_path: row.get(7)?,
        notes: row.get(8)?,
    })
}

fn build_prompt_title(proposal: &ProposalDetail) -> String {
    format!(
        "Prompt - {} - {} - {}",
        proposal.proposal_number,
        proposal.client_name_snapshot.clone().unwrap_or_default(),
        proposal.project_name.clone().unwrap_or_default()
    )
}

fn build_prompt_text(proposal: &ProposalDetail) -> String {
    let subtotal = proposal.items.iter().map(|item| item.line_total).sum::<f64>();
    let total_status = if (subtotal - proposal.total_amount).abs() <= 0.01 {
        "OK"
    } else {
        "ERRO"
    };
    let item_rows = proposal
        .items
        .iter()
        .map(|item| {
            format!(
                "{} | {} | {} | {} | {} | {} | {:.2} | {} | {:.2} | {:.2} | {}",
                item.brand_name_snapshot.clone().unwrap_or_default(),
                item.option_group.clone().unwrap_or_default(),
                item.reference,
                item.description.clone().unwrap_or_default(),
                item.finish.clone().unwrap_or_default(),
                item.quantity,
                item.original_unit_price.unwrap_or(0.0),
                format_rule(item.calculation_factor),
                item.final_unit_price,
                item.line_total,
                item.notes.clone().unwrap_or_default()
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let line_validations = proposal
        .items
        .iter()
        .map(|item| {
            let expected = (item.final_unit_price * item.quantity * 100.0).round() / 100.0;
            let status = if (expected - item.line_total).abs() <= 0.01 {
                "OK"
            } else {
                "ERRO"
            };
            format!(
                "- {}: {} - {:.2} x {} = {:.2}",
                item.reference, status, item.final_unit_price, item.quantity, expected
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "# Objetivo\n\nCriar uma proposta comercial/técnica em português de Portugal, com estrutura clara, tabelas organizadas e valores devidamente validados.\n\n# Contexto da proposta\n\n- Número: {}\n- Título: {}\n- Tipo: {}\n- Data: {}\n- Idioma: {}\n- Moeda: {}\n- Modo IVA: {}\n- Estado: {}\n\n# Dados do cliente e projeto\n\n- Cliente: {}\n- Projeto: {}\n- Local: {}\n- Validade: {}\n- Notas: {}\n\n# Layout a seguir\n\n- Layout: {}\n- Layout ID: {}\n- Tipo de proposta: {}\n\nSeguir a estrutura do layout selecionado e organizar a proposta por marcas/opções quando aplicável.\n\n# Condições comerciais\n\n{}\n\n# Regras de cálculo aplicadas\n\n- Regra: {}\n- Código: {}\n- ID: {}\n- Fator: {}\n- roundingMode: {}\n\nNão confundir multiplicar por 1,15 com dividir por 0,85. A regra de divisão por 0,85 usa arredondamento comercial para cima ao cêntimo quando o roundingMode é ceil_2_decimals.\n\n# Artigos da proposta\n\nMarca | Grupo/Opção | Referência | Descrição | Acabamento | Quantidade | Preço original | Regra/Fator | Preço final | Total da linha | Observações\n--- | --- | --- | --- | --- | ---: | ---: | --- | ---: | ---: | ---\n{}\n\n# Totais e validações\n\n- Subtotal calculado: {:.2}\n- Total da proposta: {:.2}\n- Validação do total geral: {}\n\nValidações por linha:\n\n{}\n\nConfirmar novamente que:\n\n- line_total = final_unit_price × quantity\n- proposal_total = soma dos line_total\n\n# Instruções de preservação de layout\n\n- Não alterar a estrutura visual definida.\n- Não redesenhar tabelas sem necessidade.\n- Manter a organização por marca/opção.\n- Não inventar produtos, links, imagens ou fichas técnicas.\n- Não alterar preços, quantidades ou totais.\n\n# Notas obrigatórias\n\n- Aos valores apresentados acresce IVA a taxa legal em vigor.\n- Fichas técnicas, imagens e links devem ser confirmados por referência oficial.\n\n# Resultado pretendido\n\nCriar texto de proposta pronto a converter para documento comercial. Usar português de Portugal, tom profissional, claro e comercial, e incluir tabelas organizadas.\n\n# Validações antes de terminar\n\n1. Todos os artigos estão incluídos.\n2. Todos os preços finais respeitam a regra definida.\n3. Todos os totais de linha estão corretos.\n4. O total geral corresponde à soma das linhas.\n5. A nota de IVA está presente.\n6. Não foram inventadas referências, imagens ou links.\n7. O layout e estrutura foram respeitados.",
        proposal.proposal_number,
        proposal.title,
        proposal.proposal_type.clone().unwrap_or_default(),
        proposal.proposal_date,
        proposal.language,
        proposal.currency,
        proposal.vat_mode,
        proposal.status,
        proposal.client_name_snapshot.clone().unwrap_or_default(),
        proposal.project_name.clone().unwrap_or_default(),
        proposal.project_location.clone().unwrap_or_default(),
        proposal.validity_text.clone().unwrap_or_default(),
        proposal.notes.clone().unwrap_or_default(),
        proposal.layout_name.clone().unwrap_or_default(),
        proposal.layout_id.map(|id| id.to_string()).unwrap_or_default(),
        proposal.proposal_type.clone().unwrap_or_default(),
        proposal.commercial_conditions.clone().unwrap_or_else(|| "Aos valores apresentados acresce IVA a taxa legal em vigor.".to_string()),
        proposal.pricing_rule_name.clone().unwrap_or_default(),
        proposal.pricing_rule_code.clone().unwrap_or_default(),
        proposal.pricing_rule_id.map(|id| id.to_string()).unwrap_or_default(),
        proposal.pricing_rule_factor.map(|factor| factor.to_string()).unwrap_or_default(),
        proposal.pricing_rule_rounding_mode.clone().unwrap_or_else(|| "ceil_2_decimals".to_string()),
        item_rows,
        subtotal,
        proposal.total_amount,
        total_status,
        line_validations
    )
}

fn format_rule(factor: Option<f64>) -> String {
    match factor {
        Some(value) if value != 0.0 => format!("÷ {}", value),
        _ => "-".to_string(),
    }
}
